name: Deploy Studio Preview

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - 'feat/studio_*'
      - 'fix/studio_*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
      - name: Install Rush.js
        run: npm install -g @microsoft/rush
      - name: Install dependencies
        run: rush install --to studio
      - name: Build
        run: rush build --to studio

      - name: Clear Unused Files
        run: rm -rf ./packages/app-entry/dist/*.json

      - name: Deploy Static Files to OSS
        run: |
          npm install -g @serverless-devs/s
          s config add --AccessKeyID ${{ secrets.ACCESSKEYID }} --AccessKeySecret ${{ secrets.ACCESSKEYSECRET }} -a default
          s studio-oss deploy -y

      - name: Copy Files to Vercel Output
        run: |
          mkdir -p ./.vercel/output/static
          cp ./packages/app-entry/dist/html/main/index.html ./.vercel/output/static/index.html
          cp ./packages/app-entry/vercel-config.json ./.vercel/output/config.json

      - name: Deploy App to Vercel
        run: |
          npm install --global vercel@latest
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --build-env PREVIEW=true
